// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/log/:planExId": {
    params: {
      "planExId": string;
    };
  };
  "/complete": {
    params: {};
  };
  "/history": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/log/:planExId" | "/complete" | "/history";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/log.$planExId.tsx": {
    id: "routes/log.$planExId";
    page: "/log/:planExId";
  };
  "routes/complete.tsx": {
    id: "routes/complete";
    page: "/complete";
  };
  "routes/history.tsx": {
    id: "routes/history";
    page: "/history";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/log.$planExId": typeof import("./app/routes/log.$planExId.tsx");
  "routes/complete": typeof import("./app/routes/complete.tsx");
  "routes/history": typeof import("./app/routes/history.tsx");
};